import { Scene3D } from './Scene3D.js';
import { STORYBOARD } from './storyboard-data.js';
await document.fonts.ready;
const stage=new Scene3D(document.querySelector('#board-view'));
if(!stage.paused)stage.toggleMotion();
const lifetime=new AbortController();const on=(node,event,handler)=>node.addEventListener(event,handler,{signal:lifetime.signal});
let sceneIndex=0,frameIndex=0,raf=0,playing=false,start=0;
const list=document.querySelector('#scene-list'),frames=document.querySelector('#frames'),slider=document.querySelector('#board-progress'),play=document.querySelector('#play-scene');
STORYBOARD.forEach(scene=>{const button=document.createElement('button');button.className='scene-nav-button';button.dataset.scene=scene.index;button.innerHTML=`<img src="assets/ascent-${scene.index}.png" alt=""><div><span>${String(scene.index).padStart(2,'0')} / ${scene.section.toUpperCase()}</span><strong>${scene.name}</strong></div>`;on(button,'click',()=>selectScene(scene.index));list.append(button);});
function stop(){playing=false;cancelAnimationFrame(raf);raf=0;play.textContent='Воспроизвести';}
function updatePreview(progress,time=0){const scene=STORYBOARD[sceneIndex];stage.preview(sceneIndex,progress,time);if(stage.failed){const nearest=scene.frames.reduce((best,f)=>Math.abs(f.p-progress)<Math.abs(best.p-progress)?f:best);stage.fallback.src=`assets/storyboard/${nearest.code}.png`;}document.querySelector('#view-phase').textContent=`${Math.round(progress*100)}%`;slider.value=Math.round(progress*100);}
function setFrame(index,halt=true){if(halt)stop();frameIndex=index;const frame=STORYBOARD[sceneIndex].frames[index];if(frame.format)stage.setFormat(frame.format);document.querySelector('#frame-code').textContent=frame.code;document.querySelector('#shot-code').textContent=`КАДР ${frame.code} / ${Math.round(frame.p*100)}%`;document.querySelector('#shot-title').textContent=frame.title;document.querySelector('#shot-action').textContent=frame.action;document.querySelector('#shot-detail').textContent=frame.detail;frames.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-pressed',String(i===index)));updatePreview(frame.p,frame.p*6);}
function selectScene(index){stop();sceneIndex=index;const scene=STORYBOARD[index];document.querySelector('#chapter-meta').textContent=`${String(index).padStart(2,'0')} / ${scene.section.toUpperCase()}`;document.querySelector('#chapter-title').textContent=scene.name;for(const name of ['idea','camera','objects','student','tutor','light','exit'])document.querySelector(`#scene-${name}`).textContent=scene[name];list.querySelectorAll('button').forEach(button=>button.setAttribute('aria-current',String(Number(button.dataset.scene)===index)));frames.replaceChildren(...scene.frames.map((frame,i)=>{const button=document.createElement('button');button.className='frame-button';button.innerHTML=`<img src="assets/storyboard/${frame.code}.png" alt="Кадр ${frame.code}: ${frame.title}"><span>${frame.code} / ${Math.round(frame.p*100)}%</span><strong>${frame.title}</strong>`;on(button,'click',()=>setFrame(i));return button;}));document.querySelector('#previous-scene').disabled=index===0;document.querySelector('#next-scene').disabled=index===7;setFrame(0);}
on(slider,'input',()=>{stop();const p=Number(slider.value)/100;updatePreview(p,p*6);const nearest=STORYBOARD[sceneIndex].frames.reduce((best,f,i)=>Math.abs(f.p-p)<Math.abs(STORYBOARD[sceneIndex].frames[best].p-p)?i:best,0);if(nearest!==frameIndex){const value=slider.value;setFrame(nearest);slider.value=value;updatePreview(p,p*6);}});
on(play,'click',()=>{if(playing){stop();return;}playing=true;start=performance.now();play.textContent='Пауза';const tick=now=>{if(!playing||!stage.visible||document.hidden){stop();return;}const p=Math.min(1,(now-start)/7000);updatePreview(p,p*7);if(p<1)raf=requestAnimationFrame(tick);else{stop();setFrame(3);}};raf=requestAnimationFrame(tick);});
on(document.querySelector('#previous-scene'),'click',()=>selectScene(sceneIndex-1));on(document.querySelector('#next-scene'),'click',()=>selectScene(sceneIndex+1));
if(stage.motionPreference.matches){play.disabled=true;document.querySelector('#motion-note').hidden=false;}
on(window,'pagehide',()=>{stop();lifetime.abort();stage.destroy();});selectScene(0);
