import * as THREE from '../vendor/three.module.js';
import { BaseScene } from './BaseScene.js';
import { StudentFigure } from '../objects/StudentFigure.js';
import { TutorFigure } from '../objects/TutorFigure.js';
import { platform,desk,palette } from '../objects/Props.js';
export class PricingScene extends BaseScene {
  constructor(){super({index:6,title:'FIND YOUR RHYTHM.',kicker:'ИНДИВИДУАЛЬНО · ПАРА · МИНИ-ГРУППА',cameraOffset:[12,9,-15],focus:[0,2.4,0],radius:6.7});}
  build(anchor){super.build(anchor);this.levels=[];const specs=[['individual',1,palette.lime,'1:1'],['pair',2,palette.teal,'PAIR'],['group',4,palette.amber,'GROUP']];specs.forEach(([key,count,color,title],i)=>{const g=new THREE.Group();g.position.set([-2.4,1.8,-.5][i],i*2.25,[1.4,0,1.4][i]);const base=platform(2.35,'#4b574b');base.material.emissive.set(color);g.add(base);const people=[];if(i<2){for(let n=0;n<count;n++){const t=desk();t.scale.setScalar(.45);t.position.set((n-(count-1)/2)*1.25,0,0);const f=new StudentFigure(color);f.scale.setScalar(.52);f.position.set(t.position.x,0,-.7);f.pose('sit');g.add(t,f);people.push(f);}}else{const table=desk({round:true});table.scale.setScalar(.6);g.add(table);for(let n=0;n<4;n++){const a=n*Math.PI/2;const f=new StudentFigure(color);f.scale.setScalar(.5);f.position.set(Math.sin(a)*1.2,0,Math.cos(a)*1.2);f.rotation.y=a+Math.PI;f.pose('sit');g.add(f);people.push(f);}}const trainer=new TutorFigure();trainer.scale.setScalar(.55);trainer.position.set(1.1,0,.1);g.add(trainer);const light=new THREE.PointLight(color,12,9);light.position.set(0,3,0);g.add(light);this.group.add(g);this.caption(title,[g.position.x,g.position.y+2,g.position.z],color,2);this.levels.push({key,g,base,people,trainer,light,selection:0});});this.particles(140,{color:palette.amber,range:7,height:7,speed:.25});return this;}
  update(p,time,delta,state){super.update(p,time,delta);this.levels.forEach(level=>{const target=level.key===state.format?1:0;level.selection=state.instant?target:level.selection+(target-level.selection)*Math.min(1,delta*6);level.base.material.emissiveIntensity=.03+level.selection*.35;level.light.intensity=5+level.selection*25;level.people.forEach((f,i)=>{f.userData.restPosition??=f.position.clone();f.userData.restRotation??=f.rotation.y;f.position.copy(f.userData.restPosition);f.rotation.y=f.userData.restRotation;const hero=i===0&&Boolean(target);f.pose(hero?'stand':'sit');if(hero){f.position.z=-1.6;f.rotation.y=0;}f.body.scale.y=1+Math.sin(time+i)*.01;});level.trainer.pose('stand');if(level.key==='group')level.trainer.position.x=Math.sin(time*.3)*.5;});}
}
