import * as THREE from '../vendor/three.module.js';
import { BaseScene } from './BaseScene.js';
import { StudentFigure } from '../objects/StudentFigure.js';
import { TutorFigure } from '../objects/TutorFigure.js';
import { desk,monitor,microphone,cup,briefcase,board,door,chair,label,box,palette } from '../objects/Props.js';
import { Particles } from '../objects/Particles.js';
import { smoothstep } from '../utils/easing.js';
export class ProgramsScene extends BaseScene {
  constructor(){super({index:3,title:'CHOOSE YOUR WAY.',kicker:'ЧЕТЫРЕ ЗАДАЧИ / ТВОЙ МАРШРУТ',cameraOffset:[.4,14,-5],focus:[0,.7,0],radius:5.7});}
  build(anchor){super.build(anchor);this.floor(2.3,'#48514a');this.student=new StudentFigure();this.student.position.set(-.45,0,-.5);this.student.updateColor(.8);this.tutor=new TutorFigure();this.tutor.position.set(.75,0,-.5);this.group.add(this.student,this.tutor);this.paths=[];const specs=[['it',palette.teal,'IT'],['life',palette.lime,'LIFE'],['business',palette.amber,'BUSINESS'],['interview',palette.orange,'INTERVIEW']];
    specs.forEach(([key,color,title],i)=>{const route=new THREE.Group();route.rotation.y=i*Math.PI/2+Math.PI/4;const road=box([1.35,.1,4.8],color,[0,0,3.45],{emissive:color,emissiveIntensity:.15,transparent:true});route.add(road);const props=new THREE.Group();props.position.set(0,.07,3.8);route.add(props);if(i===0){const t=desk();t.scale.setScalar(.65);const m=monitor('> code_',palette.teal);m.scale.setScalar(.65);props.add(t,m);}if(i===1){const t=desk();t.scale.setScalar(.45);const mic=microphone();mic.position.set(-.16,.52,0);const c=cup();c.position.set(.23,.5,0);props.add(t,mic,c);for(const s of [-1,1]){const f=new StudentFigure();f.scale.setScalar(.5);f.position.set(s*.65,0,0);f.rotation.y=-s*Math.PI/2;props.add(f);}}if(i===2){props.add(briefcase());const b=board('GROWTH',color);b.scale.setScalar(.5);b.position.z=.6;props.add(b);}if(i===3){const d=door();d.scale.setScalar(.6);d.position.z=.8;const seat=chair();seat.scale.setScalar(.7);const cv=label('CV',{color:'#242a2a',bg:palette.paper,width:.5,height:.7,billboard:false});cv.position.set(.35,.9,0);props.add(d,seat,cv);}const caption=label(title,{color,width:2,height:.4});caption.position.set(0,1.5,5.15);route.add(caption);const sparks=new Particles(45,{color,range:1.2,height:2,speed:.4});sparks.position.z=3.5;route.add(sparks);this.sparks.push(sparks);this.group.add(route);this.paths.push({key,route,road,color:new THREE.Color(color),angle:route.rotation.y,props});});return this;}
  update(p,time,delta,state){super.update(p,time,delta);const merge=smoothstep(.83,1,p);this.paths.forEach((path,i)=>{const reveal=smoothstep(i*.12,i*.12+.22,p+.16);path.route.scale.setScalar(Math.max(.001,reveal));path.route.rotation.y=path.angle*(1-merge);const active=path.key===state.program;path.road.material.opacity=merge?1:(active?1:.34);path.road.material.emissiveIntensity=active?.65:.05;path.road.material.color.copy(path.color).lerp(new THREE.Color(palette.lime),merge);path.props.visible=merge<.6;});this.tutor.pose('point');this.tutor.rotation.y=Math.floor(time*.35)%4*Math.PI/2;this.student.rotation.y=Math.sin(time*.3)*.14;}
}
