import * as THREE from '../vendor/three.module.js';
import { BaseScene } from './BaseScene.js';
import { StudentFigure } from '../objects/StudentFigure.js';
import { TutorFigure } from '../objects/TutorFigure.js';
import { box,cylinder,plant,line,palette } from '../objects/Props.js';
import { lerp } from '../utils/lerp.js';
export class ProgressScene extends BaseScene {
  constructor(){super({index:4,title:'LOOK HOW FAR.',kicker:'ПОДЪЁМ / ПРАКТИКА СТАНОВИТСЯ РЕЧЬЮ',cameraOffset:[7,5,-10],focus:[0,1.6,0],radius:4.9});}
  build(anchor){super.build(anchor);this.floor(4.8,'#485149');this.road=new THREE.Group();this.group.add(this.road);this.route=new THREE.CatmullRomCurve3([[-3,0,-2],[-1,.2,1],[1,.5,1.5],[2.5,1.2,.1],[1.1,1.7,-1.5]].map(p=>new THREE.Vector3(...p)));const points=this.route.getPoints(34);for(let i=0;i<points.length-1;i++){const tile=box([1.5,.12,.43],'#8ba77a',points[i].toArray());tile.rotation.y=-Math.atan2(points[i+1].x-points[i].x,points[i+1].z-points[i].z);this.road.add(tile);}this.student=new StudentFigure();this.tutor=new TutorFigure();this.group.add(this.student,this.tutor);this.graphs=[];this.plants=[];for(let i=0;i<3;i++){const x=-2.8+i*2.5;this.group.add(cylinder(.33,1.5,'#697767',[x,.75,2.5],6));const chart=line([[x-.22,.35,2.85],[x-.1,.52,2.85],[x+.05,.61,2.85],[x-.08,.93,2.85],[x+.2,1.2,2.85]],palette.lime);this.group.add(chart);this.graphs.push(chart);const flower=plant();flower.position.set(x,0,-2.5);this.group.add(flower);this.plants.push(flower);}const warm=new THREE.PointLight(palette.amber,55,18);warm.position.set(-1,5,-3);this.group.add(warm);this.particles(220,{color:palette.lime,range:8,height:6,speed:.55,size:.026});return this;}
  update(p,time,delta){super.update(p,time,delta);const point=this.route.getPoint(.08+p*.82);this.student.position.copy(point);this.student.position.y+=.09;const tangent=this.route.getTangent(.08+p*.82);this.student.rotation.y=Math.atan2(tangent.x,tangent.z);this.student.scale.setScalar(lerp(.9,1.3,p));this.student.updateColor(.6+p*.4);this.student.pose('walk',p,time);this.tutor.position.copy(this.route.getPoint(Math.min(.98,.2+p*.75)));this.tutor.position.x-=.65;this.tutor.rotation.y=this.student.rotation.y;this.tutor.pose('walk',p,time);this.graphs.forEach(chart=>chart.geometry.setDrawRange(0,Math.max(2,Math.round(2+p*3))));this.plants.forEach((flower,i)=>flower.userData.leaves.forEach((leaf,j)=>leaf.rotation.z=(j%2?1:-1)*p*.95));this.sparks.forEach(s=>s.material.uniforms.speed.value=.35+p*.7);}
}
